FROM debian:stretch-20200803-slim

ENV RUBY_VERSION 1.8.7-p374
ENV PATH /usr/local/rvm/gems/ruby-${RUBY_VERSION}@global/bin:/usr/local/rvm/gems/ruby-${RUBY_VERSION}/bin:/usr/local/rvm/rubies/ruby-${RUBY_VERSION}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin
ENV GEM_HOME /usr/local/rvm/gems/ruby-${RUBY_VERSION}@global
ENV GEM_PATH /usr/local/rvm/rubies/ruby-${RUBY_VERSION}/bin/ruby

RUN apt-get update && apt-get -y install bash procps curl wget gcc bzip2 libxml2-dev libxslt-dev linux-headers-amd64 tzdata git libcurl4-openssl-dev libpcre3-dev patch zlib1g-dev liblzma-dev build-essential libpq-dev libmariadb-dev  && apt-get clean 
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
RUN printf "deb http://security.ubuntu.com/ubuntu bionic-security main\n" >> /etc/apt/sources.list
RUN apt-get update && wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz && tar -xzf openssl-1.0.2l.tar.gz && cd openssl-1.0.2l && ./config --prefix=/opt/old-ssl shared && make && make install && cd .. && rm -rf openssl*

RUN gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && \
    curl -sSL https://get.rvm.io | bash -s -- --version 1.29.7
RUN apt install libssl1.0-dev
RUN RUN rvm install 1.8.7-p374 --with-openssl-dir=/opt/old-ssl

WORKDIR /tmp
RUN NODE_FILENAME=`curl -L -s https://nodejs.org/dist/v0.8.26 | grep 'linux-x64.tar.gz' | grep -oP '(?<=")\S*(?=")'` && \
    NODE_VERSION_TO_INSTALL=`curl -L -s https://nodejs.org/dist/v0.8.26 | grep 'linux-x64.tar.gz' | grep -oP '(?<=")\S*(?=")' | grep -oP '^\S*(?=.tar.gz)'` && \
    curl -o $NODE_FILENAME "https://nodejs.org/dist/v0.8.26/${NODE_FILENAME}" && \
    curl -o SHASUMS256.txt https://nodejs.org/dist/v0.8.26/SHASUMS256.txt && \
    grep $NODE_FILENAME SHASUMS256.txt | sha256sum -c - && \
    mkdir -p /opt/nodejs && \
    tar -xf $NODE_FILENAME -C /opt/nodejs/ && \
    rm -rf /tmp/* && \
    ln -s /opt/nodejs/$NODE_VERSION_TO_INSTALL/bin/node /usr/bin/node && \
    ln -s /opt/nodejs/$NODE_VERSION_TO_INSTALL/bin/npm /usr/bin/npm 

CMD ["irb"]